# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(300, 20, 141, 71))
        self.btn_search.setObjectName("btn_search")
        self.cmb_search_mode = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_search_mode.setGeometry(QtCore.QRect(50, 30, 69, 22))
        self.cmb_search_mode.setObjectName("cmb_search_mode")
        self.cmb_search_mode.addItem("")
        self.cmb_search_mode.addItem("")
        self.lineEdit_query = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_query.setGeometry(QtCore.QRect(50, 80, 151, 20))
        self.lineEdit_query.setObjectName("lineEdit_query")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 110, 531, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 110, 531, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.btns_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.btns_layout.setContentsMargins(0, 0, 0, 0)
        self.btns_layout.setObjectName("btns_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.btns_layout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Каталог библиотеки"))
        self.btn_search.setText(_translate("MainWindow", "Искать"))
        self.cmb_search_mode.setItemText(0, _translate("MainWindow", "Автор"))
        self.cmb_search_mode.setItemText(1, _translate("MainWindow", "Название"))
